name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true

      - name: Run Unit Tests
        run: go test ./...

      - name: Run End-to-End Test
        run: go test -tags=e2e -v ./e2e
